from __future__ import annotations


STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "for",
    "from",
    "how",
    "in",
    "into",
    "is",
    "of",
    "on",
    "or",
    "the",
    "to",
    "with",
    "your",
}


PHRASE_TO_CONCEPT = {
    "artificial intelligence": ["ai"],
    "machine learning": ["ai"],
    "health ai": ["healthcare", "ai"],
    "digital health": ["healthcare"],
    "clinical workflow": ["healthcare", "workflow"],
    "hospital operations": ["healthcare", "workflow"],
    "renewable energy": ["climate", "energy"],
    "climate tech": ["climate"],
    "clean tech": ["climate"],
    "clean energy": ["climate", "energy"],
    "decarbonization software": ["climate", "software"],
    "cross border": ["fintech"],
    "cross-border": ["fintech"],
    "bank partner": ["fintech", "partnerships"],
    "bank partnerships": ["fintech", "partnerships"],
    "enterprise pilots": ["partnerships", "pilot"],
    "pilot design": ["pilot", "partnerships"],
    "warm introductions": ["community", "networking"],
    "customer discovery": ["partnerships"],
    "developer tools": ["developer_tools"],
    "workflow automation": ["workflow", "ai"],
    "agent platform": ["ai", "developer_tools"],
    "grid software": ["energy", "software", "climate"],
    "carbon accounting": ["climate", "carbon"],
    "care delivery": ["healthcare"],
}


TOKEN_TO_CONCEPT = {
    "ai": ["ai"],
    "agent": ["ai"],
    "agents": ["ai"],
    "llm": ["ai"],
    "copilot": ["ai"],
    "ml": ["ai"],
    "workflow": ["workflow"],
    "automation": ["workflow", "ai"],
    "developer": ["developer_tools"],
    "devtools": ["developer_tools"],
    "tooling": ["developer_tools"],
    "climate": ["climate"],
    "energy": ["energy", "climate"],
    "grid": ["energy", "climate"],
    "renewable": ["climate", "energy"],
    "decarbonization": ["climate", "carbon"],
    "carbon": ["carbon", "climate"],
    "sustainability": ["climate"],
    "health": ["healthcare"],
    "healthcare": ["healthcare"],
    "clinical": ["healthcare"],
    "hospital": ["healthcare"],
    "provider": ["healthcare"],
    "care": ["healthcare"],
    "fintech": ["fintech"],
    "payments": ["fintech"],
    "payment": ["fintech"],
    "banking": ["fintech"],
    "bank": ["fintech"],
    "regtech": ["fintech", "compliance"],
    "compliance": ["compliance"],
    "risk": ["compliance"],
    "fraud": ["cybersecurity", "compliance"],
    "cybersecurity": ["cybersecurity"],
    "security": ["cybersecurity"],
    "identity": ["cybersecurity"],
    "community": ["community"],
    "networking": ["community", "networking"],
    "intro": ["networking"],
    "introductions": ["networking"],
    "partner": ["partnerships"],
    "partnerships": ["partnerships"],
    "pilot": ["pilot"],
    "pilots": ["pilot"],
    "mentor": ["mentorship"],
    "mentors": ["mentorship"],
    "advisor": ["mentorship"],
    "investor": ["funding"],
    "investors": ["funding"],
    "fundraising": ["funding"],
    "funding": ["funding"],
    "capital": ["funding"],
    "seed": ["seed_stage"],
    "pre": ["pre_seed_stage"],
    "preseed": ["pre_seed_stage"],
    "pre-seed": ["pre_seed_stage"],
    "customer": ["customers"],
    "customers": ["customers"],
    "buyers": ["customers"],
    "sales": ["customers"],
}


CANONICAL_ROLE_ALIASES = {
    "investors": "investor",
    "founders": "founder",
    "mentors": "mentor",
    "participants": "participant",
    "sessions": "session",
    "resources": "resource",
    "sponsors": "resource",
}

